//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESP_GOSTToolSheetAddIn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESP_GOSTToolSheetAddIn.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА! Значение нового параметра не задано !.
        /// </summary>
        internal static string msgNewParamError {
            get {
                return ResourceManager.GetString("msgNewParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\ToolName.txt.
        /// </summary>
        internal static string txtPathToolType {
            get {
                return ResourceManager.GetString("txtPathToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to espTool.
        /// </summary>
        internal static string xmlElementName {
            get {
                return ResourceManager.GetString("xmlElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EspritToolsParameters.xml.
        /// </summary>
        internal static string xmlPathToolsParams {
            get {
                return ResourceManager.GetString("xmlPathToolsParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolID.
        /// </summary>
        internal static string xmlToolID {
            get {
                return ResourceManager.GetString("xmlToolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolLabel.
        /// </summary>
        internal static string xmlToolLabel {
            get {
                return ResourceManager.GetString("xmlToolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolName.
        /// </summary>
        internal static string xmlToolName {
            get {
                return ResourceManager.GetString("xmlToolName", resourceCulture);
            }
        }
    }
}
